apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: dev-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: myapp
        image: tony5164/library:latest
        ports:
        - containerPort: 9002
        envFrom:
        - secretRef:
            name: db-secrets
        - secretRef:
            name: secretkey
        livenessProbe:
          httpGet:
            path: /health
            port: 9002
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"