apiVersion: v1
kind: Secret
metadata:
  name: secretKey
type: Opaque
data:
  SECRET_KEY: "mkijnhygbsnabdgahdfwhwugevdjjqgedd nsjafxssnagsqacstabkfsdcavs"

  #never use secrets for secret Keys or db secrets. only testing