apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-go
  name: my-sql
spec:
  selector:
    matchLabels:
      app: my-sql
  template:
    metadata:
      labels:
        app: my-sql
    spec:
      containers:
      - name: my-sql
        image: mysql:8.0
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: dbPassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: dbName
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: dbUser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: dbPassword
        ports:
        - containerPort: 3306
