apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: myapp
        image: tony5164/library:latest
        ports:
        - containerPort: 9002
        envFrom:
        - secretRef:
            name: db-secrets